version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: calendar
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abc@123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
